run:
    sudo darwin-rebuild switch --flake .#illusion --impure --refresh

update:
    nix flake update

index:
    nix run 'nixpkgs#nix-index' --extra-experimental-features 'nix-command flakes'

repair:
    sudo nix-store --verify --check-contents --repair
